### ISSUE TITLE
Name aus der modDesc.xml auslesen

### ISSUE THREAD

**Issue by clanfreak1988** [clanfreak1988/LS19_Mod_Manager_Release#9]
Für ein besseres Naming, sollte der Modname aus der modDesc.xml ausgelesen werden

**Comment by Dr4K4n** [comment]
Find ich gut, irgendwann könnte man auch das Store-Bild auslesen und die in der Liste anzeigen :-D

**Comment by clanfreak1988** [comment]
Weitere Idee ist das man Maps mit einer anderen Farbe darstellt
